[package]
name = "mdf"
version = "0.2.0"
edition = "2024"
description = "MDFive, simple md5 tool"
license = "MIT"

[dependencies]
md5 = "0.8.0"

[profile.release]
codegen-units = 1
opt-level = "z"
panic = "abort"
strip = true
lto = true
